server:
  port: 8082
  servlet:
    context-path: /api-2
    
spring:
  application:
    name: api-2
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    fetch-registry: true
    register-with-eureka: true