server:
  port: 8081
  servlet:
    context-path: /api-1
    
spring:
  application:
    name: api-1
    
  security:
    oauth2:
      resourceserver:
        client-id: client_app_1
        client-secret: client_app_1
        jwt:
          jwk-set-uri: http://localhost:8080/oauth-server/oauth/check_token
    
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    fetch-registry: true
    register-with-eureka: true