server:
  port: 8080
  servlet:
    context-path: /oauth-server
  error:
    whitelabel:
      enabled: false

spring:
    datasource:
        hikari:
            connection-test-query: SELECT 1 FROM DUAL
            minimum-idle: 1
            maximum-pool-size: 5
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/oauth2?serverTimezone=UTC
        username: root
        password: root
        initialization-mode: always
    jpa:
      hibernate:
        ddl-auto: update
      database: mysql  
      
eureka:
  instance:
    prefer-ip-address: true
    hostname: localhost
    port: 8084
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/