server:
  port: 8083
  servlet:
    context-path: /gateway
    
spring:
  application:
    name: gateway

security:
  oauth2:
    resource:
      jwt:
        key-value: teste
    
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    oauth:
      path: /oauth/**
      sensitiveHeaders: 
      url: http://localhost:8080/oauth-server/oauth
    api-1:
      path: /api-1/**
      url: http://localhost:8081/api-1
    api-2:
      path: /api-2/**
      url: http://localhost:8082/api-2
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8084/eureka/
    fetch-registry: true
    register-with-eureka: true